### ISSUE TITLE
关于在地狱世界死亡后重生时报错的问题

### ISSUE THREAD

**Issue by AnsonSkywalker** [AbstractPrinter/SuperRespawn#1]
一份相同内容的反馈已经发至MCBBS。
这里是原版1.12的PaperSpigot，插件能够正常运行。
本人的服务器是单世界（主世界、地狱、末地）小型服务器，经过测试后发现：在主世界的主城设置过唯一的重生点后，玩家在地狱死亡时该插件无法有效地接管重生系统，表现为玩家重生在最后睡过的床（原版默认），而不是主城的重生点。与此同时出现以下报错信息：

[01:53:03] [Server thread/ERROR]: Could not pass event PlayerRespawnEvent to SuperRespawn v1.1.2.202101061413_Release
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[PaperSpigot-1.12-b1167.jar:git-Paper-1167]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.12-b1167.jar:git-Paper-1167]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.12-b1167.jar:git-Paper-1167]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[PaperSpigot-1.12-b1167.jar:git-Paper-1167]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[PaperSpigot-1.12-b1167.jar:git-Paper-1167]
	at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:682) ~[PaperSpigot-1.12-b1167.jar:git-Paper-1167]
	at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:610) ~[PaperSpigot-1.12-b1167.jar:git-Paper-1167]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1695) ~[PaperSpigot-1.12-b1167.jar:git-Paper-1167]
	at net.minecraft.server.v1_12_R1.PacketPlayInClientCommand.a(SourceFile:31) ~[PaperSpigot-1.12-b1167.jar:git-Paper-1167]
	at net.minecraft.server.v1_12_R1.PacketPlayInClientCommand.a(SourceFile:8) ~[PaperSpigot-1.12-b1167.jar:git-Paper-1167]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PaperSpigot-1.12-b1167.jar:git-Paper-1167]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_271]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_271]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-1.12-b1167.jar:git-Paper-1167]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [PaperSpigot-1.12-b1167.jar:git-Paper-1167]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [PaperSpigot-1.12-b1167.jar:git-Paper-1167]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [PaperSpigot-1.12-b1167.jar:git-Paper-1167]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [PaperSpigot-1.12-b1167.jar:git-Paper-1167]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.NullPointerException
	at cn.wangyudi.superrespawn.listeners.RespawnListener.onNearestSpawn(RespawnListener.java:59) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor146.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[PaperSpigot-1.12-b1167.jar:git-Paper-1167]
	... 18 more

在主世界死亡时插件可以正常接管重生系统（重生在插件设置的重生点），无报错无BUG。
考虑到在地狱另设重生点并不十分妥当，恳请在下个版本修复此问题。

**Comment by AnsonSkywalker** [comment]
追加，在地狱世界设置重生点后在地狱死亡可以正常复活在设置的重生点，无报错无BUG。

**Comment by AbstractPrinter** [comment]
可不可以附加一份`data.db`文件

**Comment by AnsonSkywalker** [comment]
你要的关于SuperRespawn插件的DB文件https://airportal.cn/613318/5inCJALOeu

**Comment by AbstractPrinter** [comment]
已经完成修复，请在`Jenkins`获取最新版本。
